package ch.uprisesoft.jconstruct.executor;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * A line of output from a running command
 *
 * Has a type of INFO or ERROR, an id and the text from the command output. This
 * is a immutable class
 *
 * @author Uprise Software <uprisesoft@gmail.com>
 */
public class OutputEntry {

    private static int idCounter = 1;

    private final Integer id;
    private final OutputEntryType type;
    private final LocalDateTime timestamp;
    private final String entry;
    private final Set<String> tags;

    protected OutputEntry(Integer id, LocalDateTime timestamp, String entry, OutputEntryType type, Set<String> tags) {
        this.id = id;
        this.timestamp = timestamp;
        this.type = type;
        this.entry = entry;
        this.tags = tags;
    }

    /**
     *
     * Public constructor for command output lines
     *
     * You should instantiate this class only for testing purpose. Normally, it
     * is generated by a CommandRunner
     *
     * @param entry: the string from the command output
     * @param type: the type of the entry. May be INFO or ERROR
     */
    public OutputEntry(String entry, OutputEntryType type, Set<String> tags) {
        this.id = idCounter;
        idCounter++;
        this.timestamp = LocalDateTime.now();
        this.type = type;
        this.entry = entry;
        this.tags = tags;
    }

    public Integer getId() {
        return id;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public OutputEntryType getType() {
        return type;
    }

    public String getEntry() {
        return entry;
    }

    public Set<String> getTags() {
        return tags;
    }
    
    public boolean hasTag(String tag) {
        return tags.contains(tag);
    }
}
